name: Update privaterepo in README
on: [create, workflow_dispatch]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Update link in README
        run: sed -ri "s#(https://mdenet-ep.sites.er.kcl.ac.uk/\?activities=)(.*)(&privaterepo=true)#\1https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}/activity.json\3#" README.md
      - name: Commit changes to README
        run: |
          git config --global user.name 'update-privaterepo-link workflow'
          git config --global user.email 'szschaler@users.noreply.github.com'
          git add README.md
          git commit -m "Automated update of privaterepo link"
          git push